// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /nix/store/4dxx74s4g3rrn6haryx8i6yzy91f5q7m-source
// from /nix/store/687zj3l24wawn3a93nkqqcv6g0hjm9n5-dbusmenu-gtk3-gir
// DO NOT EDIT

mod client;
pub use self::client::Client;

mod menuitem;
pub use self::menuitem::Menuitem;

mod menuitem_proxy;
pub use self::menuitem_proxy::MenuitemProxy;

mod server;
pub use self::server::Server;

mod enums;
pub use self::enums::Status;
pub use self::enums::TextDirection;

pub mod traits {
    pub use super::client::ClientExt;
    pub use super::menuitem::MenuitemExt;
    pub use super::menuitem_proxy::MenuitemProxyExt;
    pub use super::server::ServerExt;
}
